# Generated by Django 4.2 on 2023-04-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='complete_date',
            field=models.DateTimeField(verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
