# Generated by Django 4.2 on 2023-04-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='content',
            field=models.CharField(max_length=250, null=True, verbose_name='Задача'),
        ),
    ]
